spring.application.name=demo.holamundo
server.port=8088

# ===== CONEXIÓN A POSTGRESQL LOCAL =====
spring.datasource.url=jdbc:postgresql://localhost:5432/sistema_simple
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# ===== JPA/HIBERNATE PARA POSTGRESQL =====
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ===== THYMELEAF =====
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.cache=false

# ===== MANEJO DE ERRORES =====
server.error.whitelabel.enabled=false
server.error.path=/error
server.error.include-exception=true
server.error.include-message=always
server.error.include-stacktrace=always

# ===== LOGGING =====
logging.level.org.springframework.web=INFO
logging.level.com.example.demo=DEBUG
logging.level.org.hibernate.SQL=DEBUG


# ===== CONFIGURACIÓN PARA SUBIR ARCHIVOS =====
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
spring.servlet.multipart.enabled=true

# ===== IMGBB =====
imgbb.api.key=2287c899c31a05580bcc63797272e536